### ISSUE TITLE
false errors for OEM links

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-URI-Validator#1]
I have a redfish service that represents UPI ports on a CPU. Standard schemas do not provide a way to do this, so inside a Processor resource we have:

```
    "Oem": {
        "Hpe": {
            "Ports": {
                "@odata.id": "<Processor URI>/Ports"
```

And that leads to a collection of ports, using the standard Port and PortCollection resources. These don't conform to the list of acceptable "Port" URIs, but from what I understand, that is OK if it is linked under OEM.

**Comment by mraineri** [comment]
Currently we're expecting standard resources to only be at standard URIs; need to think of a way to accommodate OEM usage of standard resources.
