### ISSUE TITLE
issue moved to other repository

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-URI-Validator#13]
Hi,

I raised an issue yesterday. When I would like to check it today, I find it is moved to another repository. Please let me know how to track it. Thanks.

![err](https://user-images.githubusercontent.com/21072491/69696116-a3e88280-1119-11ea-9a15-7fe353469e4a.JPG)

**Comment by mraineri** [comment]
Sorry, I thought you would have access to that issue.

Since redfish/v1/Chassis/{ChassisId}/LogServices isn't listed in openapi.yaml, technically it is an illegal URI. However, this appears to be a mistake and it should be part of the openapi.yaml file. We'll need to fix this in our publication.

**Comment by snk20501** [comment]
@mraineri No worries. Thanks for the confirmation.

**Comment by mraineri** [comment]
Closing 1/9; original issue being handled in the schema files
