### ISSUE TITLE
Validator ignored invalid URI

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-URI-Validator#16]
I had a redfish implementation that incorrectly used /redfish/v1/Schemas instead of /redfish/v1/JsonSchemas. This was caught by Redfish-Service-Validator, but not Redfish-URI-Validator. This tool didn't mention that resource/URI at all in the RedfishURITestReport html document it created.

**Comment by blakehilliard** [comment]
This was using a fresh clone of this repo on this date, and a local copy of the latest http://redfish.dmtf.org/schemas/v1/openapi.yaml passed to the tool with the "-o" option

**Comment by mraineri** [comment]
We haven't been maintaining this since we added URI validation to the Service Validator. Is there a need to fix this?

**Comment by blakehilliard** [comment]
I don't see any indication that this tool is no longer supported? But I'm happy to drop running this if Redfish-Service-Validator is meant to cover everything this was meant to cover.

**Comment by mraineri** [comment]
I added a deprecation notice to the readme.
