### ISSUE TITLE
Redfish URI Validator require odata.id for PrivilegeRegistry URI

### ISSUE THREAD

**Issue by vien20010** [DMTF/Redfish-URI-Validator#17]
Following Redfish spec DSP0266 1.11, session 38.1 https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.11.2.pdf, PrivilegeRegistry may include @odata.id (optional)
![image](https://github.com/DMTF/Redfish-URI-Validator/assets/52381847/3676ff2c-dc13-433b-94e2-100408d1e6fb)
and DMTF doesn’t define @odata.id for https://redfish.dmtf.org/registries/Redfish_1.1.0_PrivilegeRegistry.json. But Redfish URI Validator tool is required this property for all include PrivilegeRegistry so this is a tool issue. This opinion is confirmed by DMTF following this topic https://redfishforum.com/thread/994/odata-missing-redfish-privilegeregistry-json.
Please review and have solution for it.

**Comment by mraineri** [comment]
I'd recommend moving away from this tool. We have a deprecation notice in the readme. We can certainly take pull requests if needed, but DMTF isn't actively updating the tool.

From the readme:

## Deprecated

This tool is deprecated in favor of URI checking functionality that has been folded into the the [Redfish-Service-Validator](https://github.com/DMTF/Redfish-Service-Validator).

**Comment by mraineri** [comment]
Closing; will not be fixing given the tool is deprecated
