### ISSUE TITLE
false errors for Bios Settings resources

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-URI-Validator#2]
If a Bios resource has a @Redfish.Settings resource, with a URI like /redfish/v1/Systems/1/Bios/Settings, redfish-uri-validator will flag that as an error. But this conforms with examples in the redfish schema guide.

**Comment by mraineri** [comment]
This will also be an issue with Action Info and Collection Capabilities since we do not explicitly call out their URIs either.
