### ISSUE TITLE
ERROR: Could not log into target

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-URI-Validator#8]
Hi,

I try the latest code and can't log into the target with correct credential. The ERROR always shows after program ruining for a while. Please help to check.

**Comment by billdodd** [comment]
I tested the latest code against a couple of services and did not see any errors.

Can you please provide the exact output of the command, including the error message?

**Comment by snk20501** [comment]
@billdodd Please refer to attached snapshot. I use curl command to get the target service root first and you can see it success. 
![snapshot](https://user-images.githubusercontent.com/21072491/65938040-6b4b6600-e454-11e9-8782-80c8e531b99f.JPG)

**Comment by mraineri** [comment]
Can you access other resources with the same credentials? Service Root doesn't require authentication. Can you also create a session with those credentials?

**Comment by billdodd** [comment]
@snk20501 - If you confirm the creds are correct per @mraineri's suggestion above, please clone the branch for PR #9 and give that a try. It should display the call stack of the exception received. That will likely help with narrowing down the problem.

**Comment by snk20501** [comment]
@billdodd @mraineri From below debug output, can see tool shows error when it access one invalid URI in our product as an issue. 
![snapshot](https://user-images.githubusercontent.com/21072491/66019794-5a175d80-e517-11e9-831c-25250e4469ee.JPG)

**Comment by mraineri** [comment]
@snk20501 could you please try updating your version of the "redfish" module? We just published version 2.1.3, which should handle this.

**Comment by snk20501** [comment]
@mraineri @billdodd after update latest modules, it works now.
